version: 2
updates:
  # Root dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  # Client dependencies
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"

  # Cloud Functions dependencies
  - package-ecosystem: "npm"
    directory: "/functions"
    schedule:
      interval: "weekly"
